// source: package/package.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.packagetrip.Flight', null, global);
goog.exportSymbol('proto.packagetrip.Hotel', null, global);
goog.exportSymbol('proto.packagetrip.PackageCreate', null, global);
goog.exportSymbol('proto.packagetrip.PackageCreateRequest', null, global);
goog.exportSymbol('proto.packagetrip.PackageResponse', null, global);
goog.exportSymbol('proto.packagetrip.PackageSearch', null, global);
goog.exportSymbol('proto.packagetrip.PackageSearchRequest', null, global);
goog.exportSymbol('proto.packagetrip.PackageSearchResponse', null, global);
goog.exportSymbol('proto.packagetrip.PackagesByUserRequest', null, global);
goog.exportSymbol('proto.packagetrip.PackagesResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.packagetrip.PackageSearch = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.packagetrip.PackageSearch, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.packagetrip.PackageSearch.displayName = 'proto.packagetrip.PackageSearch';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.packagetrip.PackageSearchResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.packagetrip.PackageSearchResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.packagetrip.PackageSearchResponse.displayName = 'proto.packagetrip.PackageSearchResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.packagetrip.PackageSearchRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.packagetrip.PackageSearchRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.packagetrip.PackageSearchRequest.displayName = 'proto.packagetrip.PackageSearchRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.packagetrip.Flight = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.packagetrip.Flight, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.packagetrip.Flight.displayName = 'proto.packagetrip.Flight';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.packagetrip.Hotel = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.packagetrip.Hotel, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.packagetrip.Hotel.displayName = 'proto.packagetrip.Hotel';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.packagetrip.PackageCreate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.packagetrip.PackageCreate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.packagetrip.PackageCreate.displayName = 'proto.packagetrip.PackageCreate';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.packagetrip.PackageCreateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.packagetrip.PackageCreateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.packagetrip.PackageCreateRequest.displayName = 'proto.packagetrip.PackageCreateRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.packagetrip.PackageResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.packagetrip.PackageResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.packagetrip.PackageResponse.displayName = 'proto.packagetrip.PackageResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.packagetrip.PackagesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.packagetrip.PackagesResponse.repeatedFields_, null);
};
goog.inherits(proto.packagetrip.PackagesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.packagetrip.PackagesResponse.displayName = 'proto.packagetrip.PackagesResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.packagetrip.PackagesByUserRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.packagetrip.PackagesByUserRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.packagetrip.PackagesByUserRequest.displayName = 'proto.packagetrip.PackagesByUserRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.packagetrip.PackageSearch.prototype.toObject = function(opt_includeInstance) {
  return proto.packagetrip.PackageSearch.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.packagetrip.PackageSearch} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.packagetrip.PackageSearch.toObject = function(includeInstance, msg) {
  var f, obj = {
    originlocationcode: jspb.Message.getFieldWithDefault(msg, 1, ""),
    destinationlocationcode: jspb.Message.getFieldWithDefault(msg, 2, ""),
    departuredate: jspb.Message.getFieldWithDefault(msg, 3, ""),
    returndate: jspb.Message.getFieldWithDefault(msg, 4, ""),
    adults: jspb.Message.getFieldWithDefault(msg, 5, 0),
    children: jspb.Message.getFieldWithDefault(msg, 6, 0),
    infants: jspb.Message.getFieldWithDefault(msg, 7, 0),
    travelclass: jspb.Message.getFieldWithDefault(msg, 8, ""),
    roomquantity: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.packagetrip.PackageSearch}
 */
proto.packagetrip.PackageSearch.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.packagetrip.PackageSearch;
  return proto.packagetrip.PackageSearch.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.packagetrip.PackageSearch} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.packagetrip.PackageSearch}
 */
proto.packagetrip.PackageSearch.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOriginlocationcode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDestinationlocationcode(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeparturedate(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setReturndate(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAdults(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setChildren(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setInfants(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setTravelclass(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRoomquantity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.packagetrip.PackageSearch.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.packagetrip.PackageSearch.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.packagetrip.PackageSearch} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.packagetrip.PackageSearch.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOriginlocationcode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDestinationlocationcode();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDeparturedate();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getReturndate();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getAdults();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getChildren();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getInfants();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getTravelclass();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getRoomquantity();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
};


/**
 * optional string originLocationCode = 1;
 * @return {string}
 */
proto.packagetrip.PackageSearch.prototype.getOriginlocationcode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.packagetrip.PackageSearch} returns this
 */
proto.packagetrip.PackageSearch.prototype.setOriginlocationcode = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string destinationLocationCode = 2;
 * @return {string}
 */
proto.packagetrip.PackageSearch.prototype.getDestinationlocationcode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.packagetrip.PackageSearch} returns this
 */
proto.packagetrip.PackageSearch.prototype.setDestinationlocationcode = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string departureDate = 3;
 * @return {string}
 */
proto.packagetrip.PackageSearch.prototype.getDeparturedate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.packagetrip.PackageSearch} returns this
 */
proto.packagetrip.PackageSearch.prototype.setDeparturedate = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string returnDate = 4;
 * @return {string}
 */
proto.packagetrip.PackageSearch.prototype.getReturndate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.packagetrip.PackageSearch} returns this
 */
proto.packagetrip.PackageSearch.prototype.setReturndate = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int64 adults = 5;
 * @return {number}
 */
proto.packagetrip.PackageSearch.prototype.getAdults = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.packagetrip.PackageSearch} returns this
 */
proto.packagetrip.PackageSearch.prototype.setAdults = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int64 children = 6;
 * @return {number}
 */
proto.packagetrip.PackageSearch.prototype.getChildren = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.packagetrip.PackageSearch} returns this
 */
proto.packagetrip.PackageSearch.prototype.setChildren = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int64 infants = 7;
 * @return {number}
 */
proto.packagetrip.PackageSearch.prototype.getInfants = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.packagetrip.PackageSearch} returns this
 */
proto.packagetrip.PackageSearch.prototype.setInfants = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional string travelClass = 8;
 * @return {string}
 */
proto.packagetrip.PackageSearch.prototype.getTravelclass = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.packagetrip.PackageSearch} returns this
 */
proto.packagetrip.PackageSearch.prototype.setTravelclass = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional int64 roomQuantity = 9;
 * @return {number}
 */
proto.packagetrip.PackageSearch.prototype.getRoomquantity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.packagetrip.PackageSearch} returns this
 */
proto.packagetrip.PackageSearch.prototype.setRoomquantity = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.packagetrip.PackageSearchResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.packagetrip.PackageSearchResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.packagetrip.PackageSearchResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.packagetrip.PackageSearchResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    pb_package: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.packagetrip.PackageSearchResponse}
 */
proto.packagetrip.PackageSearchResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.packagetrip.PackageSearchResponse;
  return proto.packagetrip.PackageSearchResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.packagetrip.PackageSearchResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.packagetrip.PackageSearchResponse}
 */
proto.packagetrip.PackageSearchResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPackage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.packagetrip.PackageSearchResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.packagetrip.PackageSearchResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.packagetrip.PackageSearchResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.packagetrip.PackageSearchResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPackage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string package = 1;
 * @return {string}
 */
proto.packagetrip.PackageSearchResponse.prototype.getPackage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.packagetrip.PackageSearchResponse} returns this
 */
proto.packagetrip.PackageSearchResponse.prototype.setPackage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.packagetrip.PackageSearchRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.packagetrip.PackageSearchRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.packagetrip.PackageSearchRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.packagetrip.PackageSearchRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    packagesearch: (f = msg.getPackagesearch()) && proto.packagetrip.PackageSearch.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.packagetrip.PackageSearchRequest}
 */
proto.packagetrip.PackageSearchRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.packagetrip.PackageSearchRequest;
  return proto.packagetrip.PackageSearchRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.packagetrip.PackageSearchRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.packagetrip.PackageSearchRequest}
 */
proto.packagetrip.PackageSearchRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.packagetrip.PackageSearch;
      reader.readMessage(value,proto.packagetrip.PackageSearch.deserializeBinaryFromReader);
      msg.setPackagesearch(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.packagetrip.PackageSearchRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.packagetrip.PackageSearchRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.packagetrip.PackageSearchRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.packagetrip.PackageSearchRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPackagesearch();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.packagetrip.PackageSearch.serializeBinaryToWriter
    );
  }
};


/**
 * optional PackageSearch packageSearch = 1;
 * @return {?proto.packagetrip.PackageSearch}
 */
proto.packagetrip.PackageSearchRequest.prototype.getPackagesearch = function() {
  return /** @type{?proto.packagetrip.PackageSearch} */ (
    jspb.Message.getWrapperField(this, proto.packagetrip.PackageSearch, 1));
};


/**
 * @param {?proto.packagetrip.PackageSearch|undefined} value
 * @return {!proto.packagetrip.PackageSearchRequest} returns this
*/
proto.packagetrip.PackageSearchRequest.prototype.setPackagesearch = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.packagetrip.PackageSearchRequest} returns this
 */
proto.packagetrip.PackageSearchRequest.prototype.clearPackagesearch = function() {
  return this.setPackagesearch(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.packagetrip.PackageSearchRequest.prototype.hasPackagesearch = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.packagetrip.Flight.prototype.toObject = function(opt_includeInstance) {
  return proto.packagetrip.Flight.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.packagetrip.Flight} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.packagetrip.Flight.toObject = function(includeInstance, msg) {
  var f, obj = {
    intinerantes: jspb.Message.getFieldWithDefault(msg, 1, ""),
    price: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.packagetrip.Flight}
 */
proto.packagetrip.Flight.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.packagetrip.Flight;
  return proto.packagetrip.Flight.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.packagetrip.Flight} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.packagetrip.Flight}
 */
proto.packagetrip.Flight.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setIntinerantes(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrice(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.packagetrip.Flight.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.packagetrip.Flight.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.packagetrip.Flight} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.packagetrip.Flight.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIntinerantes();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPrice();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string intinerantes = 1;
 * @return {string}
 */
proto.packagetrip.Flight.prototype.getIntinerantes = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.packagetrip.Flight} returns this
 */
proto.packagetrip.Flight.prototype.setIntinerantes = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string price = 2;
 * @return {string}
 */
proto.packagetrip.Flight.prototype.getPrice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.packagetrip.Flight} returns this
 */
proto.packagetrip.Flight.prototype.setPrice = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.packagetrip.Hotel.prototype.toObject = function(opt_includeInstance) {
  return proto.packagetrip.Hotel.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.packagetrip.Hotel} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.packagetrip.Hotel.toObject = function(includeInstance, msg) {
  var f, obj = {
    hotel: jspb.Message.getFieldWithDefault(msg, 1, ""),
    offers: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.packagetrip.Hotel}
 */
proto.packagetrip.Hotel.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.packagetrip.Hotel;
  return proto.packagetrip.Hotel.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.packagetrip.Hotel} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.packagetrip.Hotel}
 */
proto.packagetrip.Hotel.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHotel(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOffers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.packagetrip.Hotel.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.packagetrip.Hotel.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.packagetrip.Hotel} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.packagetrip.Hotel.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHotel();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOffers();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string hotel = 1;
 * @return {string}
 */
proto.packagetrip.Hotel.prototype.getHotel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.packagetrip.Hotel} returns this
 */
proto.packagetrip.Hotel.prototype.setHotel = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string offers = 2;
 * @return {string}
 */
proto.packagetrip.Hotel.prototype.getOffers = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.packagetrip.Hotel} returns this
 */
proto.packagetrip.Hotel.prototype.setOffers = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.packagetrip.PackageCreate.prototype.toObject = function(opt_includeInstance) {
  return proto.packagetrip.PackageCreate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.packagetrip.PackageCreate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.packagetrip.PackageCreate.toObject = function(includeInstance, msg) {
  var f, obj = {
    userid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    flight: (f = msg.getFlight()) && proto.packagetrip.Flight.toObject(includeInstance, f),
    hotel: (f = msg.getHotel()) && proto.packagetrip.Hotel.toObject(includeInstance, f),
    amount: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    off: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.packagetrip.PackageCreate}
 */
proto.packagetrip.PackageCreate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.packagetrip.PackageCreate;
  return proto.packagetrip.PackageCreate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.packagetrip.PackageCreate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.packagetrip.PackageCreate}
 */
proto.packagetrip.PackageCreate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    case 2:
      var value = new proto.packagetrip.Flight;
      reader.readMessage(value,proto.packagetrip.Flight.deserializeBinaryFromReader);
      msg.setFlight(value);
      break;
    case 3:
      var value = new proto.packagetrip.Hotel;
      reader.readMessage(value,proto.packagetrip.Hotel.deserializeBinaryFromReader);
      msg.setHotel(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setAmount(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setOff(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.packagetrip.PackageCreate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.packagetrip.PackageCreate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.packagetrip.PackageCreate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.packagetrip.PackageCreate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFlight();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.packagetrip.Flight.serializeBinaryToWriter
    );
  }
  f = message.getHotel();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.packagetrip.Hotel.serializeBinaryToWriter
    );
  }
  f = message.getAmount();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getOff();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
};


/**
 * optional string userId = 1;
 * @return {string}
 */
proto.packagetrip.PackageCreate.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.packagetrip.PackageCreate} returns this
 */
proto.packagetrip.PackageCreate.prototype.setUserid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Flight flight = 2;
 * @return {?proto.packagetrip.Flight}
 */
proto.packagetrip.PackageCreate.prototype.getFlight = function() {
  return /** @type{?proto.packagetrip.Flight} */ (
    jspb.Message.getWrapperField(this, proto.packagetrip.Flight, 2));
};


/**
 * @param {?proto.packagetrip.Flight|undefined} value
 * @return {!proto.packagetrip.PackageCreate} returns this
*/
proto.packagetrip.PackageCreate.prototype.setFlight = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.packagetrip.PackageCreate} returns this
 */
proto.packagetrip.PackageCreate.prototype.clearFlight = function() {
  return this.setFlight(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.packagetrip.PackageCreate.prototype.hasFlight = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Hotel hotel = 3;
 * @return {?proto.packagetrip.Hotel}
 */
proto.packagetrip.PackageCreate.prototype.getHotel = function() {
  return /** @type{?proto.packagetrip.Hotel} */ (
    jspb.Message.getWrapperField(this, proto.packagetrip.Hotel, 3));
};


/**
 * @param {?proto.packagetrip.Hotel|undefined} value
 * @return {!proto.packagetrip.PackageCreate} returns this
*/
proto.packagetrip.PackageCreate.prototype.setHotel = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.packagetrip.PackageCreate} returns this
 */
proto.packagetrip.PackageCreate.prototype.clearHotel = function() {
  return this.setHotel(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.packagetrip.PackageCreate.prototype.hasHotel = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional float amount = 4;
 * @return {number}
 */
proto.packagetrip.PackageCreate.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.packagetrip.PackageCreate} returns this
 */
proto.packagetrip.PackageCreate.prototype.setAmount = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional float off = 5;
 * @return {number}
 */
proto.packagetrip.PackageCreate.prototype.getOff = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.packagetrip.PackageCreate} returns this
 */
proto.packagetrip.PackageCreate.prototype.setOff = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.packagetrip.PackageCreateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.packagetrip.PackageCreateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.packagetrip.PackageCreateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.packagetrip.PackageCreateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    packagecreate: (f = msg.getPackagecreate()) && proto.packagetrip.PackageCreate.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.packagetrip.PackageCreateRequest}
 */
proto.packagetrip.PackageCreateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.packagetrip.PackageCreateRequest;
  return proto.packagetrip.PackageCreateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.packagetrip.PackageCreateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.packagetrip.PackageCreateRequest}
 */
proto.packagetrip.PackageCreateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.packagetrip.PackageCreate;
      reader.readMessage(value,proto.packagetrip.PackageCreate.deserializeBinaryFromReader);
      msg.setPackagecreate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.packagetrip.PackageCreateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.packagetrip.PackageCreateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.packagetrip.PackageCreateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.packagetrip.PackageCreateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPackagecreate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.packagetrip.PackageCreate.serializeBinaryToWriter
    );
  }
};


/**
 * optional PackageCreate packageCreate = 1;
 * @return {?proto.packagetrip.PackageCreate}
 */
proto.packagetrip.PackageCreateRequest.prototype.getPackagecreate = function() {
  return /** @type{?proto.packagetrip.PackageCreate} */ (
    jspb.Message.getWrapperField(this, proto.packagetrip.PackageCreate, 1));
};


/**
 * @param {?proto.packagetrip.PackageCreate|undefined} value
 * @return {!proto.packagetrip.PackageCreateRequest} returns this
*/
proto.packagetrip.PackageCreateRequest.prototype.setPackagecreate = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.packagetrip.PackageCreateRequest} returns this
 */
proto.packagetrip.PackageCreateRequest.prototype.clearPackagecreate = function() {
  return this.setPackagecreate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.packagetrip.PackageCreateRequest.prototype.hasPackagecreate = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.packagetrip.PackageResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.packagetrip.PackageResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.packagetrip.PackageResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.packagetrip.PackageResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    flight: (f = msg.getFlight()) && proto.packagetrip.Flight.toObject(includeInstance, f),
    hotel: (f = msg.getHotel()) && proto.packagetrip.Hotel.toObject(includeInstance, f),
    amount: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    off: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    updatedat: jspb.Message.getFieldWithDefault(msg, 6, 0),
    createdat: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.packagetrip.PackageResponse}
 */
proto.packagetrip.PackageResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.packagetrip.PackageResponse;
  return proto.packagetrip.PackageResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.packagetrip.PackageResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.packagetrip.PackageResponse}
 */
proto.packagetrip.PackageResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.packagetrip.Flight;
      reader.readMessage(value,proto.packagetrip.Flight.deserializeBinaryFromReader);
      msg.setFlight(value);
      break;
    case 3:
      var value = new proto.packagetrip.Hotel;
      reader.readMessage(value,proto.packagetrip.Hotel.deserializeBinaryFromReader);
      msg.setHotel(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setAmount(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setOff(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUpdatedat(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.packagetrip.PackageResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.packagetrip.PackageResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.packagetrip.PackageResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.packagetrip.PackageResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFlight();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.packagetrip.Flight.serializeBinaryToWriter
    );
  }
  f = message.getHotel();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.packagetrip.Hotel.serializeBinaryToWriter
    );
  }
  f = message.getAmount();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getOff();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getUpdatedat();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getCreatedat();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.packagetrip.PackageResponse.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.packagetrip.PackageResponse} returns this
 */
proto.packagetrip.PackageResponse.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Flight flight = 2;
 * @return {?proto.packagetrip.Flight}
 */
proto.packagetrip.PackageResponse.prototype.getFlight = function() {
  return /** @type{?proto.packagetrip.Flight} */ (
    jspb.Message.getWrapperField(this, proto.packagetrip.Flight, 2));
};


/**
 * @param {?proto.packagetrip.Flight|undefined} value
 * @return {!proto.packagetrip.PackageResponse} returns this
*/
proto.packagetrip.PackageResponse.prototype.setFlight = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.packagetrip.PackageResponse} returns this
 */
proto.packagetrip.PackageResponse.prototype.clearFlight = function() {
  return this.setFlight(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.packagetrip.PackageResponse.prototype.hasFlight = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Hotel hotel = 3;
 * @return {?proto.packagetrip.Hotel}
 */
proto.packagetrip.PackageResponse.prototype.getHotel = function() {
  return /** @type{?proto.packagetrip.Hotel} */ (
    jspb.Message.getWrapperField(this, proto.packagetrip.Hotel, 3));
};


/**
 * @param {?proto.packagetrip.Hotel|undefined} value
 * @return {!proto.packagetrip.PackageResponse} returns this
*/
proto.packagetrip.PackageResponse.prototype.setHotel = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.packagetrip.PackageResponse} returns this
 */
proto.packagetrip.PackageResponse.prototype.clearHotel = function() {
  return this.setHotel(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.packagetrip.PackageResponse.prototype.hasHotel = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional float amount = 4;
 * @return {number}
 */
proto.packagetrip.PackageResponse.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.packagetrip.PackageResponse} returns this
 */
proto.packagetrip.PackageResponse.prototype.setAmount = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional float off = 5;
 * @return {number}
 */
proto.packagetrip.PackageResponse.prototype.getOff = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.packagetrip.PackageResponse} returns this
 */
proto.packagetrip.PackageResponse.prototype.setOff = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional int64 updatedAt = 6;
 * @return {number}
 */
proto.packagetrip.PackageResponse.prototype.getUpdatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.packagetrip.PackageResponse} returns this
 */
proto.packagetrip.PackageResponse.prototype.setUpdatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int64 createdAt = 7;
 * @return {number}
 */
proto.packagetrip.PackageResponse.prototype.getCreatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.packagetrip.PackageResponse} returns this
 */
proto.packagetrip.PackageResponse.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.packagetrip.PackagesResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.packagetrip.PackagesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.packagetrip.PackagesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.packagetrip.PackagesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.packagetrip.PackagesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    packageresponseList: jspb.Message.toObjectList(msg.getPackageresponseList(),
    proto.packagetrip.PackageResponse.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.packagetrip.PackagesResponse}
 */
proto.packagetrip.PackagesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.packagetrip.PackagesResponse;
  return proto.packagetrip.PackagesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.packagetrip.PackagesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.packagetrip.PackagesResponse}
 */
proto.packagetrip.PackagesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.packagetrip.PackageResponse;
      reader.readMessage(value,proto.packagetrip.PackageResponse.deserializeBinaryFromReader);
      msg.addPackageresponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.packagetrip.PackagesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.packagetrip.PackagesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.packagetrip.PackagesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.packagetrip.PackagesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPackageresponseList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.packagetrip.PackageResponse.serializeBinaryToWriter
    );
  }
};


/**
 * repeated PackageResponse packageResponse = 1;
 * @return {!Array<!proto.packagetrip.PackageResponse>}
 */
proto.packagetrip.PackagesResponse.prototype.getPackageresponseList = function() {
  return /** @type{!Array<!proto.packagetrip.PackageResponse>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.packagetrip.PackageResponse, 1));
};


/**
 * @param {!Array<!proto.packagetrip.PackageResponse>} value
 * @return {!proto.packagetrip.PackagesResponse} returns this
*/
proto.packagetrip.PackagesResponse.prototype.setPackageresponseList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.packagetrip.PackageResponse=} opt_value
 * @param {number=} opt_index
 * @return {!proto.packagetrip.PackageResponse}
 */
proto.packagetrip.PackagesResponse.prototype.addPackageresponse = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.packagetrip.PackageResponse, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.packagetrip.PackagesResponse} returns this
 */
proto.packagetrip.PackagesResponse.prototype.clearPackageresponseList = function() {
  return this.setPackageresponseList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.packagetrip.PackagesByUserRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.packagetrip.PackagesByUserRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.packagetrip.PackagesByUserRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.packagetrip.PackagesByUserRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    userid: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.packagetrip.PackagesByUserRequest}
 */
proto.packagetrip.PackagesByUserRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.packagetrip.PackagesByUserRequest;
  return proto.packagetrip.PackagesByUserRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.packagetrip.PackagesByUserRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.packagetrip.PackagesByUserRequest}
 */
proto.packagetrip.PackagesByUserRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.packagetrip.PackagesByUserRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.packagetrip.PackagesByUserRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.packagetrip.PackagesByUserRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.packagetrip.PackagesByUserRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string userId = 1;
 * @return {string}
 */
proto.packagetrip.PackagesByUserRequest.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.packagetrip.PackagesByUserRequest} returns this
 */
proto.packagetrip.PackagesByUserRequest.prototype.setUserid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto.packagetrip);
